import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google'
import './globals.css'
import StoreProvider from '@/app/StoreProvider'
import HeaderSidebarProvider from '@/widgets/header/HeaderSidebarProvider'
import s from './page.module.scss'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['cyrillic', 'latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
})

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['cyrillic', 'latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: 'Dryzhnye App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {

  return (
    <html lang="ru">
    <body className={`${inter.variable} ${roboto.variable}`}>
    <StoreProvider>
      <HeaderSidebarProvider>
        {children}
      </HeaderSidebarProvider>
    </StoreProvider>
    </body>
    </html>
  )
}
