import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google'
import './globals.css'
import StoreProvider from '@/store/StoreProvider'
import HeaderSidebarProvider from '@/widgets/header/HeaderSidebarProvider'
import 'swiper/css'
import 'swiper/css/navigation'
import 'swiper/css/pagination'
import { Toaster } from 'react-hot-toast'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['cyrillic', 'latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
})

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['cyrillic', 'latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: 'Dryzhnye App',
  description: 'Generated by create next app',
  icons: {
    icon: [
      { url: '/favicons/favicon-light.svg', media: '(prefers-color-scheme: light)' },
      { url: '/favicons/favicon-dark.svg', media: '(prefers-color-scheme: dark)' },
    ],
  },
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {

  return (
    <html lang="ru">
    <head>
      <link data-rh={'true'} rel="icon" href='/favicons/favicon-light.svg' type="image/svg+xml" media="(prefers-color-scheme: dark)"/>
      <link data-rh={'true'} rel="icon" href='/favicons/faivcon-dark.svg' type="image/svg+xml" media="(prefers-color-scheme: light)"/>
    </head>
    <body className={`${inter.variable} ${roboto.variable}`}>
    <StoreProvider>
      <HeaderSidebarProvider>
        {children}
        <Toaster
          position="bottom-left"
          toastOptions={{
            duration: 3000,
            style: {
              zIndex: 999999999999999999999,
              border: '1px solid var(--success-500)',
              background: 'var(--success-900)',
              color: 'var(--light-100)',
              padding: '12px 24px',
              width: '387px',
              minHeight: '48px',
              fontSize: '16px',
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center',
            },
            success: {
              iconTheme: {
                primary: 'var(--success-500)',
                secondary: 'var(--success-900)',
              },
            },
            error: {
              style: {
                border: '1px solid var(--danger-500)',
                background: 'var(--danger-900)',
              },
              iconTheme: {
                primary: 'var(--danger-500)',
                secondary: 'var(--danger-900)',
              },
            },
          }}
        />
      </HeaderSidebarProvider>
    </StoreProvider>
    </body>
    </html>
  )
}
